### PR TITLE
update version to 0.46.0

### PR DESCRIPTION
**Pull request by ginglis13**
**Description of changes:**
- Update version to 0.46.0

**Testing done:**

- [x] Build SDK x86_64
- [x] Build SDK aarch64
- [x] Build bottlerocket-core-kit aarch64 on x86_64
- [x] Build bottlerocket-core-kit aarch64 on aarch64
- [x] Build bottlerocket-core-kit x86_64 on x86_64
- [x] Build bottlerocket-core-kit x86_64 on aarch64

With the caveat of minor changes to 3 package specs: https://github.com/bottlerocket-os/bottlerocket-sdk/pull/213#issuecomment-2405911773

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by ginglis13** [comment]
^ rebase off of #209

**Comment by ginglis13** [comment]
Build failed:

```
#230 1.532 Error: failed to detect any license from /home/builder/license-scan/license-list-data/json/details/OFL-1.0.json (hash = 0x492895c1), please add a clarification
#230 ERROR: process "/bin/sh -c /usr/libexec/tools/bottlerocket-license-scan     --clarify clarify.toml     --spdx-data /usr/libexec/tools/spdx-data     --out-dir /usr/share/licenses/bottlerocket-license-scan/vendor     cargo --locked Cargo.toml" did not complete successfully: exit code: 1
```

Looks like there's an issue with scanning licenses in the `bottlerocket-license-scan` tool itself now that it's published to crates.io via #211 

Pulled down license-list-data, ran

```
cargo run --bin bottlerocket-license-scan -- --clarify clarify.toml  --spdx-data license-list-data/json/details --out-dir test-out cargo --locked Cargo.toml
```

Locally seeing inconsistent errors between runs such as

```
Error: failed to detect any license from /home/fedora/bottlerocket-sdk/license-scan/license-list-data/json/details/CC-BY-3.0-DE.json (hash = 0x3a51d219), please add a clarification
```

I checked out 3737c49bfccfc1adf0221d055a1888d776e87cf6 and ran the scan just fine, since that doesn't scan the `bottlerocket-license-scan` crate

edit: I narrowed the remove of `publish: false` from `license-scan-tool/Cargo.toml` to be the culprit but haven't been able to dig deeper as to why.

**Comment by cbgbt** [comment]
Oddly enough, the crate isn't published yet. I was working on integrating release automation like `release-plz`. I'll take a look at this too.

**Comment by cbgbt** [comment]
Thanks for the `publish: false` pointer. We apparently don't write attributions if `publish = false` ([relevant source code](https://github.com/bottlerocket-os/bottlerocket-sdk/blob/9e055b561eba6039b0eb32f9f137775fedf43fc3/license-scan/src/main.rs#L112)).

Since publish is now unset, license-scan is attempting to scan and attribute itself. Unfortunately, if the license data or output directory are in the same directory as the license-scanner, it treats these as belonging to its own source and becomes thoroughly confused. This is because license-scanner is searching through all sources of its targets searching for license files. I replicated your test command, and basically license-scan is seeing the license files it is writing for other projects, and then becoming alarmed because license-scan knows that its licenses are supposed to be MIT or Apache-2.0, so why is there a CCA license in there?

In the SDK build itself it's failing for similar reasons. [We copy the license data into the same directory as the license scan project](https://github.com/bottlerocket-os/bottlerocket-sdk/blob/9e055b561eba6039b0eb32f9f137775fedf43fc3/Dockerfile#L689) so there's a bunch of miscellaneous licenses in the source directory for it to become confused about when it scans itself.

The reason the error is inconsistent is due to whatever inode iteration ordering we happen to get when iterating through the "source" files.

**Comment by cbgbt** [comment]
PR out to fix it here (still testing the build though): https://github.com/bottlerocket-os/bottlerocket-sdk/pull/214

I know these failures are very time consuming and am sorry @ginglis13! I tested `license-scan` using its own `Makefile` and could not imagine how flipping `publish` in the Cargo.toml file could have impacted the SDK's build 🫠.

**Comment by ginglis13** [comment]
nice @cbgbt ! Thanks for digging into this and thanks for the quick fix :D

**Comment by ginglis13** [comment]
Building the core kit on x86_64 failed:

```
  #14 107.5 /home/builder/rpmbuild/BUILDROOT/bottlerocket-early-boot-config-0.1-0.1728419136.62450eb4.br1.x86_64/x86_64-bottlerocket-linux-gnu/sys-root/usr/libexec/early-boot-config/bin/ec2-identity-doc-user-da
ta-provider must use aws-lc-rs
  #14 107.8 /home/builder/rpmbuild/BUILDROOT/bottlerocket-early-boot-config-0.1-0.1728419136.62450eb4.br1.x86_64/x86_64-bottlerocket-linux-gnu/sys-root/usr/libexec/early-boot-config/bin/ec2-imds-user-data-provi
der must use aws-lc-rs
  #14 108.3 Found 2 binaries using the wrong crypto.

...  

107.5 /home/builder/rpmbuild/BUILDROOT/bottlerocket-early-boot-config-0.1-0.1728419136.62450eb4.br1.x86_64/x86_64-bottlerocket-linux-gnu/sys-root/usr/libexec/early-boot-config/bin/ec2-identity-doc-user-data-p
rovider must use aws-lc-rs
  107.8 /home/builder/rpmbuild/BUILDROOT/bottlerocket-early-boot-config-0.1-0.1728419136.62450eb4.br1.x86_64/x86_64-bottlerocket-linux-gnu/sys-root/usr/libexec/early-boot-config/bin/ec2-imds-user-data-provider
must use aws-lc-rs
  108.3 Found 2 binaries using the wrong crypto.
```

**Comment by arnaldo2792** [comment]
Yes, you need:

```
%undefine cross_check_fips
%undefine cross_check_fips
```

In:

- `os.spec`
- `early-boot-config.spec`
- `netdog.spec`

**Review by arnaldo2792 — APPROVED** [review]

**Review by mgsharm — APPROVED** [review]

**Review by bcressey — APPROVED** [review]

**Pull request merged**
