### PR TITLE
Toolchain refresh v0.22.0

### PR DESCRIPTION
**Pull request by jpculp**
**Issue number:**

#53 

**Description of changes:**

* Buildroot to **2021.02.3**
* libunwind to **12.0.0**
* Rust to **1.53.0**
* Go to **1.16.5**
* SPDX license data to **3.13**
* small `Dockerfile` lint fix
* bump sdk version to **0.22.0**

**Testing done:**

- [x] Build SDK (and Bottlerocket) `x86_64` on `x86_64`
- [x] Build SDK (and Bottlerocket) `aarch64` on `x86_64`
- [x] Build SDK (and Bottlerocket) `aarch64` on `aarch64`
- [x] Build SDK (and Bottlerocket) `x86_64` on `aarch64`
- [x] Build Bottlerocket with Rust **nightly** toolchain
- [x] Retest after #54 merge
- [x] Test https://github.com/bottlerocket-os/bottlerocket/pull/1640
- [x] Test https://github.com/bottlerocket-os/bottlerocket/pull/1622

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by bcressey** [comment]
LGTM

**Review by tjkirch — COMMENTED** [review]
LGTM pending testing.

**Review by webern — APPROVED** [review]

**Comment by jpculp** [comment]
Retested after merging #54 and locally rebasing. Ready for review.

**Review by zmrow — APPROVED** [review]

**Review by tjkirch — APPROVED** [review]

**Review by bcressey — APPROVED** [review]

**Comment by jpculp** [comment]
Passed GitHub Actions workflow on main Bottlerocket repository.

**Comment by jpculp** [comment]
OVA uploading worked. Thanks for testing, @zmrow!

**Pull request merged**
