### PR TITLE
merge macros from the monorepo

### PR DESCRIPTION
**Pull request by bcressey**
**Issue number:**
#108

**Description of changes:**
Add the macro-related commits from the Bottlerocket repo to a new root branch, and merge it into the SDK history.

Branch created as follows:
```
git clone git@github.com:bottlerocket-os/bottlerocket.git
cd bottlerocket
git checkout -b monorepo-macros
git fast-export monorepo-macros -- macros/* >../macros.fi
cd ..
git clone git@github.com:bcressey/bottlerocket-sdk.git
cd bottlerocket-sdk
git switch --orphan monorepo-macros
git fast-import < ../macros.fi
git checkout develop
git checkout -b merge-monorepo-macros
git merge --signoff --allow-unrelated-histories monorepo-macros
git push -u origin merge-monorepo-macros
```

**Testing done:**
Branch looks OK in my local git history.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by bcressey** [comment]
From a review standpoint, I'd appreciate feedback on the Git mechanics. I've verified that the macros end up the same, so there's not any new code to look at.

I have a few other changes I want to make to macros, and I need to actually integrate them into the SDK, but I'm holding off until this goes in.

**Review by cbgbt — APPROVED** [review]
Makes sense to me and the history looks correct, but I didn't realize that git had import/export prior to reading this review, so I'm not sure how much my thumbs up is worth :smile:

**Review by webern — APPROVED** [review]

**Comment by markusboehme** [comment]
Cutting off history always is a bit unpleasant, but I'm happy we're retaining the logs. It should be reasonable easy to find related changes in the mono repo with that.

As for the Git mechanics, it's a nice use of the import functionality, too--much nicer than `filter-branch`! Having multiple roots like this in a repo may be unusual, but is fine. (For example, btrfs was brought into the Linux repo like that.)

The `macros` directory isn't changing too much, so keeping the mono^Wmain repository and the SDK repo synced is no big deal in the short term. The plan is to remove `macros` from the main repo after the next SDK release though, right?

**Review by markusboehme — APPROVED** [review]

**Review by foersleo — APPROVED** [review]

**Comment by bcressey** [comment]
> The macros directory isn't changing too much, so keeping the mono^Wmain repository and the SDK repo synced is no big deal in the short term. The plan is to remove macros from the main repo after the next SDK release though, right?

Right!

**Pull request merged**
